language: java
jdk:
  - oraclejdk8
  - oraclejdk7
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build

env:
  global:
    TERM=dumb
